(function(w){
var A=w.AulaDemo;
function card(x){var c=x.course||x,a=x.assignment||{},pct=A.percent('u-admin',c),cert=A.cert('u-admin',c.id);return '<article class="panel demo-course-card"><span class="demo-kicker">Capacitación publicada</span><h3>'+A.escape(c.title)+'</h3><p>'+A.escape(c.description)+'</p><div class="demo-progress-bar"><span style="width:'+pct+'%"></span></div><small class="demo-muted">'+pct+'% completado'+(a.due_at?' · vence '+A.escape(a.due_at):'')+'</small><div class="demo-card-actions"><a class="primary-button" href="#/course/'+encodeURIComponent(c.id)+'">'+(pct?'Continuar':'Iniciar')+'</a>'+(cert?'<a class="secondary-button" href="#/certificate/'+encodeURIComponent(cert.code)+'">Certificado</a>':'')+'</div></article>';}
A.dashboard=function(){
 var items=A.assigned('u-admin'),certs=A.state.certificates.filter(function(c){return c.user_id==='u-admin';}),avg=items.length?Math.round(items.reduce(function(s,x){return s+A.percent('u-admin',x.course);},0)/items.length):0;
 var html='<div class="page"><section class="dashboard-hero"><div><span class="hero-pill"><span class="demo-status-dot"></span> Demo local activa</span><h1>Aprende, participa y certifícate.</h1><p>Completa videos, presentaciones, recursos didácticos y actividades antes del examen final.</p><div class="hero-actions"><a class="yellow-button" href="#/catalog">Ver mis capacitaciones</a><a class="glass-button" href="#/studio">Crear capacitación</a></div></div><div class="hero-metric"><strong>'+certs.length+'</strong><span>Certificados obtenidos</span></div></section>'+
 '<section class="metric-grid"><article><div><span>Asignadas visibles</span><strong>'+items.length+'</strong></div></article><article><div><span>Certificadas</span><strong>'+certs.length+'</strong></div></article><article><div><span>Juegos disponibles</span><strong>6</strong></div></article><article><div><span>Progreso promedio</span><strong>'+avg+'%</strong></div></article></section>'+
 '<section class="section-heading"><div><span class="eyebrow">Continuar aprendizaje</span><h2>Capacitaciones asignadas</h2><p>El contenido se desbloquea de forma secuencial.</p></div><a href="#/catalog">Ver todas</a></section><div class="course-grid">'+items.slice(0,3).map(card).join('')+'</div>'+
 '<section class="section-heading" style="margin-top:34px"><div><span class="eyebrow">Actividad de demo</span><h2>Trazabilidad local</h2><p>Eventos de ejemplo almacenados en el navegador.</p></div></section><section class="panel">'+A.state.activity.slice(0,5).map(function(ev){return '<div style="padding:10px 0;border-bottom:1px solid #edf1f6"><b>'+new Date(ev.at).toLocaleString('es-CO')+'</b><div class="demo-muted">'+A.escape(ev.text)+'</div></div>';}).join('')+'</section></div>';
 document.getElementById('root').innerHTML=A.shell(html);A.bindShell();
};
A.catalog=function(){var items=A.assigned('u-admin');document.getElementById('root').innerHTML=A.shell('<div class="page"><section class="section-heading"><div><span class="eyebrow">Ruta personal</span><h1>Mis capacitaciones</h1><p>Capacitaciones publicadas y asignadas al usuario demo.</p></div></section><div class="course-grid">'+items.map(card).join('')+'</div></div>');A.bindShell();};
function blockContent(entry,done){
 var b=entry.block,type={video:'Video demostrativo',presentation:'Presentación',reading:'Lectura',game:'Actividad interactiva',validation:'Validación'}[b.type]||b.type,body='';
 if(b.type==='video'||b.type==='presentation')body='<div class="demo-media-placeholder"><div><strong>'+(b.type==='video'?'▶ ':'▣ ')+A.escape(type)+'</strong><p>Recurso simulado para la presentación comercial.</p></div></div>';
 else if(b.type==='game')body='<div class="demo-resource"><h3>Actividad · Toma una decisión</h3><p>Selecciona la acción más adecuada:</p><div class="demo-actions"><button class="secondary-button demo-choice">Actuar sin revisar</button><button class="secondary-button demo-choice correct">Revisar, decidir y dejar evidencia</button></div><p id="gameFeedback" class="demo-muted"></p></div>';
 else if(b.type==='validation')body='<div class="demo-resource"><h3>Validación rápida</h3><p>¿La trazabilidad permite reconstruir lo ocurrido?</p><div class="demo-actions"><button class="secondary-button demo-valid" data-ok="1">Sí</button><button class="secondary-button demo-valid" data-ok="0">No</button></div><p id="validationFeedback" class="demo-muted"></p></div>';
 else body='<div class="demo-stage-copy"><h3>Contenido de lectura</h3><p>'+A.escape(b.body)+'</p><p>Este contenido puede editarse desde Gestión.</p></div>';
 return '<div><span class="demo-kicker">'+A.escape(type)+'</span><h2>'+A.escape(b.title)+'</h2><p class="demo-muted">'+A.escape(b.body)+'</p>'+body+'<div class="stage-nav" style="margin-top:22px"><button id="completeBlock" class="'+(done?'secondary-button':'primary-button')+'">'+(done?'✓ Contenido completado':'Marcar como completado')+'</button></div></div>';
}
function exam(course){return '<section class="exam-panel"><span class="eyebrow">Evaluación certificable</span><h2>Examen final</h2><p>Responde 10 preguntas. Nota mínima: '+course.passing_score+'%.</p><form id="examForm">'+course.questions.map(function(q,i){return '<article class="demo-exam-question"><h3>'+(i+1)+'. '+A.escape(q.prompt)+'</h3>'+q.options.map(function(op,oi){return '<label><input type="radio" name="'+A.escape(q.id)+'" value="'+oi+'" required> <span>'+A.escape(op)+'</span></label>';}).join('')+'</article>';}).join('')+'<button class="primary-button">Enviar examen</button></form></section>';}
function result(course,res){return '<section class="exam-result '+(res.passed?'passed':'failed')+'"><div style="font-size:48px">'+(res.passed?'✓':'!')+'</div><h2>'+(res.passed?'Módulo aprobado':'Aún no alcanzas la nota mínima')+'</h2><strong>'+res.score+'%</strong><p>'+(res.passed?'Certificado generado: '+A.escape(res.code):'Repasa el contenido y vuelve a presentar el examen.')+'</p><div class="demo-actions">'+(res.passed?'<a class="primary-button" href="#/certificate/'+encodeURIComponent(res.code)+'">Abrir certificado</a>':'<button class="primary-button" id="retryExam">Reintentar</button>')+'</div></section>';}
A.courseView=function(id){
 var c=A.course(id);if(!c){location.hash='#/catalog';return;}var done=A.progress('u-admin',id),all=A.flatten(c),req=all.filter(function(x){return x.block.required;}),allDone=req.every(function(x){return done.indexOf(x.block.id)>=0;});
 if(!A.ui.selectedBlock[id]){var first=all.find(function(x){return done.indexOf(x.block.id)<0;})||all[0];A.ui.selectedBlock[id]=first?first.block.id:null;}
 var sel=A.ui.selectedBlock[id],idx=Math.max(0,all.findIndex(function(x){return x.block.id===sel;})),current=all[idx],pct=A.percent('u-admin',c),cert=A.cert('u-admin',id),center=A.ui.examCourse===id?(A.ui.lastExam&&A.ui.lastExam.courseId===id?result(c,A.ui.lastExam):exam(c)):(current?blockContent(current,done.indexOf(current.block.id)>=0):'<div class="empty-state">Sin contenidos</div>');
 var outline=c.phases.map(function(p){return '<div class="outline-phase"><strong>'+A.escape(p.title)+'</strong>'+(p.blocks||[]).map(function(b){var i=all.findIndex(function(x){return x.block.id===b.id;}),locked=all.slice(0,i).filter(function(x){return x.block.required;}).some(function(x){return done.indexOf(x.block.id)<0;}),complete=done.indexOf(b.id)>=0;return '<button class="'+(sel===b.id&&A.ui.examCourse!==id?'active':'')+'" data-block="'+A.escape(b.id)+'" '+(locked?'disabled':'')+'><span>'+(complete?'✓':locked?'🔒':i+1)+'</span><div><b>'+A.escape(b.title)+'</b><small>'+A.escape(b.type)+(b.required?' · obligatorio':' · opcional')+'</small></div></button>';}).join('')+'</div>';}).join('')+
 '<button id="launchExam" class="exam-launch" '+(!allDone?'disabled':'')+'><span>✦</span><div><b>Examen final</b><small>'+(allDone?'Aprobar con '+c.passing_score+'%':'Completa los bloques obligatorios')+'</small></div></button>';
 var html='<div class="page"><a class="secondary-button" href="#/catalog">← Volver a mis capacitaciones</a><section class="course-player-hero"><div><span class="hero-pill">'+A.escape(c.status)+'</span><h1>'+A.escape(c.title)+'</h1><p>'+A.escape(c.description)+'</p></div><div class="progress-circle"><strong>'+pct+'%</strong><span>contenido obligatorio</span></div></section>'+(cert?'<div class="form-message">Esta capacitación ya tiene certificado. <a href="#/certificate/'+encodeURIComponent(cert.code)+'">Abrir certificado</a></div>':'')+'<div class="course-player-layout"><aside class="course-outline">'+outline+'</aside><section class="course-stage">'+center+'</section></div></div>';
 document.getElementById('root').innerHTML=A.shell(html);A.bindShell();
 document.querySelectorAll('[data-block]').forEach(function(btn){btn.onclick=function(){A.ui.examCourse=null;A.ui.lastExam=null;A.ui.selectedBlock[id]=btn.getAttribute('data-block');A.courseView(id);};});
 var cb=document.getElementById('completeBlock');if(cb&&current)cb.onclick=function(){if(done.indexOf(current.block.id)<0){done.push(current.block.id);A.save();A.log('Contenido completado: '+current.block.title+' · '+c.title);A.toast('Contenido marcado como completado.');}if(all[idx+1])A.ui.selectedBlock[id]=all[idx+1].block.id;A.courseView(id);};
 document.querySelectorAll('.demo-choice').forEach(function(b){b.onclick=function(){document.getElementById('gameFeedback').textContent=b.classList.contains('correct')?'Correcto: primero verifica, decide y deja evidencia.':'Intenta de nuevo: primero debes verificar.';};});
 document.querySelectorAll('.demo-valid').forEach(function(b){b.onclick=function(){document.getElementById('validationFeedback').textContent=b.getAttribute('data-ok')==='1'?'Correcto. Esa es la finalidad de la trazabilidad.':'No. La trazabilidad sí permite reconstruir hechos.';};});
 var launch=document.getElementById('launchExam');if(launch)launch.onclick=function(){if(allDone){A.ui.examCourse=id;A.ui.lastExam=null;A.courseView(id);}};
 var form=document.getElementById('examForm');if(form)form.onsubmit=function(e){e.preventDefault();var correct=0;c.questions.forEach(function(q){var pick=form.querySelector('input[name="'+q.id+'"]:checked');if(pick&&Number(pick.value)===q.correct)correct++;});var score=Math.round(correct/c.questions.length*100),passed=score>=c.passing_score,code=null;if(passed){var existing=A.cert('u-admin',id);if(existing)code=existing.code;else{code='CERT-DEMO-'+new Date().getFullYear()+'-'+String(A.state.certificates.length+1).padStart(4,'0');A.state.certificates.push({id:A.uid('cert'),code:code,user_id:'u-admin',course_id:id,score:score,issued_at:new Date().toISOString()});A.save();A.log('Certificado generado: '+code+' · '+c.title);}}A.ui.lastExam={courseId:id,score:score,passed:passed,code:code};A.courseView(id);};
 var retry=document.getElementById('retryExam');if(retry)retry.onclick=function(){A.ui.lastExam=null;A.courseView(id);};
};
A.games=function(){var list=[['Memoria de conceptos','Une conceptos y definiciones.'],['Clasificación','Clasifica riesgos, señales o procesos.'],['Ordenar pasos','Organiza procedimientos y protocolos.'],['Búsqueda visual','Encuentra elementos dentro de una imagen.'],['Mini RPG','Recorre zonas y completa misiones.'],['Cartas de decisión','Resuelve casos y recibe retroalimentación.']];document.getElementById('root').innerHTML=A.shell('<div class="page"><section class="section-heading"><div><span class="eyebrow">Biblioteca didáctica</span><h1>Juegos de capacitación</h1><p>Plantillas demostrativas configurables.</p></div></section><div class="game-library">'+list.map(function(g,i){return '<article><div style="font-size:26px">'+(i+1)+'</div><h3>'+A.escape(g[0])+'</h3><p>'+A.escape(g[1])+'</p><span>Plantilla disponible</span></article>';}).join('')+'</div></div>');A.bindShell();};
A.certificateView=function(code){var cert=A.state.certificates.find(function(c){return c.code===code;});if(!cert){document.getElementById('root').innerHTML=A.shell('<div class="page"><div class="empty-state"><h2>Certificado no encontrado</h2><a class="primary-button" href="#/studio">Ir a Gestión</a></div></div>');A.bindShell();return;}var u=A.user(cert.user_id),c=A.course(cert.course_id),html='<div class="page"><div class="print-hide demo-actions"><a class="secondary-button" href="#/studio">← Volver</a><button id="printCert" class="primary-button">Imprimir / guardar PDF</button></div><section class="demo-certificate"><span class="demo-kicker" style="justify-content:center">Aula de Formación · Demostración</span><h1>Certificado</h1><p>Se certifica que</p><div class="recipient">'+A.escape(u?u.full_name:'Usuario Demo')+'</div><p>completó y aprobó satisfactoriamente la capacitación</p><div class="course">'+A.escape(c?c.title:'Capacitación')+'</div><p class="demo-muted">'+A.escape(c?c.description:'')+'</p><div class="meta"><span><b>Puntaje</b><br>'+cert.score+'%</span><span><b>Fecha</b><br>'+new Date(cert.issued_at).toLocaleDateString('es-CO')+'</span><span><b>Código</b><br>'+A.escape(cert.code)+'</span></div><p style="margin-top:38px"><b>Documento demostrativo · sin validez hasta implementar la versión productiva</b></p></section></div>';document.getElementById('root').innerHTML=A.shell(html);A.bindShell();document.getElementById('printCert').onclick=function(){window.print();};};
})(window);