(function (w) {
  var A = w.AulaDemo;

  function tabs() {
    var items = '<button data-tab="courses" class="' + (A.ui.tab === 'courses' ? 'active' : '') + '">Capacitaciones</button>';
    if (A.canManageUsers()) {
      items += '<button data-tab="assignments" class="' + (A.ui.tab === 'assignments' ? 'active' : '') + '">Asignaciones</button>';
      items += '<button data-tab="users" class="' + (A.ui.tab === 'users' ? 'active' : '') + '">Usuarios y roles</button>';
      items += '<button data-tab="compliance" class="' + (A.ui.tab === 'compliance' ? 'active' : '') + '">Cumplimiento</button>';
      items += '<button data-tab="certificates" class="' + (A.ui.tab === 'certificates' ? 'active' : '') + '">Ranking y certificados</button>';
    }
    return '<div class="tab-bar">' + items + '</div>';
  }
  function futureDate(days) { var d = new Date(); d.setDate(d.getDate() + days); return d.toISOString().slice(0, 10); }
  function blankQuestions(id) {
    var prompts = ['¿Cuál es el objetivo principal de este contenido?', '¿Qué acción debe realizarse primero?', '¿Qué evidencia demuestra la actividad?', '¿Cuál es la decisión más segura?', '¿Qué práctica favorece la mejora continua?', '¿Qué debe verificarse antes de continuar?', '¿Qué significa mantener trazabilidad?', '¿Cuándo debe solicitarse aclaración?', '¿Qué resultado se espera del proceso?', '¿Qué conducta reduce errores?'];
    return prompts.map(function (p, i) { return { id: id + '-q' + i, prompt: p, options: ['Opción correcta', 'Opción B', 'Opción C', 'Opción D'], correct: 0 }; });
  }
  async function persistCourse(c, message) {
    var result = await A.rpc('aula_save_course', { p_course: c });
    if (result && result.id && result.id !== c.id) c.id = result.id;
    A.localLog(message || ('Capacitación guardada: ' + c.title));
    return result;
  }

  function coursePanel() {
    if (A.ui.selectedCourse) {
      var c = A.course(A.ui.selectedCourse); if (!c) { A.ui.selectedCourse = null; return coursePanel(); }
      return '<div class="studio-columns"><section class="panel"><div class="panel-heading"><div><h2>Editar capacitación</h2><p>Los cambios se guardan directamente en Supabase.</p></div></div><form id="editCourseForm" class="demo-inline-form">' +
        '<label>Título<input name="title" value="' + A.escape(c.title) + '" required></label><label>Nota mínima<input name="passing" type="number" min="1" max="100" value="' + c.passing_score + '" required></label>' +
        '<label class="span-2">Descripción<textarea name="description" rows="4">' + A.escape(c.description) + '</textarea></label><label>Estado<select name="status"><option value="published" ' + (c.status === 'published' ? 'selected' : '') + '>Publicado</option><option value="draft" ' + (c.status === 'draft' ? 'selected' : '') + '>Borrador</option><option value="archived" ' + (c.status === 'archived' ? 'selected' : '') + '>Archivado</option></select></label>' +
        '<div class="demo-actions"><button class="primary-button" id="saveCourseBtn">Guardar cambios</button><button type="button" class="secondary-button" id="backCourses">Volver</button></div></form></section>' +
        '<section class="panel"><div class="panel-heading"><div><h2>Contenido</h2><p>Fases y bloques de la ruta secuencial.</p></div></div>' +
        (c.phases || []).map(function (p) { return '<div style="margin-bottom:20px"><h3>' + A.escape(p.title) + '</h3>' + (p.blocks || []).map(function (b) { return '<div class="block-admin-row"><div><b>' + A.escape(b.title) + '</b><small style="display:block">' + A.escape(b.type) + (b.required ? ' · obligatorio' : ' · opcional') + '</small></div><button class="secondary-button delete-block" data-id="' + A.escape(b.id) + '">Eliminar</button></div>'; }).join('') + '</div>'; }).join('') +
        '<form id="addBlockForm" class="demo-inline-form"><label>Título<input name="title" required></label><label>Tipo<select name="type"><option value="reading">Lectura</option><option value="video">Video</option><option value="presentation">Presentación</option><option value="pdf">PDF</option><option value="image">Imagen</option><option value="audio">Audio</option><option value="link">Enlace</option><option value="game">Juego</option><option value="validation">Validación</option></select></label><label class="span-2">Contenido<textarea name="body" rows="3" required></textarea></label><label class="span-2">URL del recurso (opcional)<input name="url" type="url" placeholder="https://…"></label><label><input name="required" type="checkbox" checked> Obligatorio</label><div><button class="primary-button">Agregar bloque</button></div></form></section>' +
        '<section class="panel"><div class="panel-heading"><div><h2>Evaluación final</h2><p>La calificación se realiza en PostgreSQL; la respuesta correcta no se envía a los colaboradores.</p></div></div><div class="assignment-list">' +
        (c.questions || []).map(function (q, i) { return '<article class="assignment-card"><div><b>' + (i + 1) + '. ' + A.escape(q.prompt) + '</b><span>Correcta: ' + A.escape((q.options || [])[q.correct] || 'Sin definir') + '</span></div></article>'; }).join('') + '</div></section></div>';
    }
    return '<div class="studio-columns"><section class="panel"><div class="panel-heading"><div><h2>Nueva capacitación</h2><p>Crea una ruta con evaluación de 10 preguntas.</p></div></div><form id="newCourseForm" class="demo-inline-form"><label>Título<input name="title" required></label><label>Nota mínima<input name="passing" type="number" min="1" max="100" value="80" required></label><label class="span-2">Descripción<textarea name="description" rows="4" required></textarea></label><button class="primary-button">Crear capacitación</button></form></section>' +
      '<section class="panel"><div class="panel-heading"><div><h2>Capacitaciones</h2><p>' + A.state.courses.length + ' registros persistentes.</p></div></div><div class="assignment-list">' + A.state.courses.map(function (c) { return '<article class="assignment-card"><div><b>' + A.escape(c.title) + '</b><span>' + A.escape(c.description) + '</span><small>' + A.escape(c.status) + '</small></div><button class="secondary-button edit-course" data-id="' + A.escape(c.id) + '">Editar</button></article>'; }).join('') + '</div></section></div>';
  }

  function assignmentsPanel() {
    return '<div class="studio-columns"><section class="panel"><div class="panel-heading"><div><h2>Nueva asignación</h2><p>Relaciona una membresía activa con una capacitación.</p></div></div><form id="assignForm" class="demo-inline-form"><label>Usuario<select name="user">' + A.state.users.filter(function (u) { return u.is_active; }).map(function (u) { return '<option value="' + u.id + '">' + A.escape(u.full_name) + '</option>'; }).join('') + '</select></label><label>Capacitación<select name="course">' + A.state.courses.filter(function (c) { return c.status !== 'archived'; }).map(function (c) { return '<option value="' + A.escape(c.id) + '">' + A.escape(c.title) + '</option>'; }).join('') + '</select></label><label>Vencimiento<input name="due" type="date" value="' + futureDate(15) + '"></label><div><button class="primary-button">Asignar</button></div></form></section>' +
      '<section class="panel"><div class="panel-heading"><div><h2>Asignaciones activas</h2><p>Quitar una asignación no elimina el progreso ni certificados históricos.</p></div></div><div class="assignment-list">' + (A.state.assignments.length ? A.state.assignments.map(function (a) { var u = A.user(a.user_id), c = A.course(a.course_id); return '<article class="assignment-card"><div><b>' + A.escape(c ? c.title : 'Capacitación no disponible') + '</b><span>' + A.escape(u ? u.full_name : 'Usuario no disponible') + '</span><small>' + (a.due_at ? 'Vence ' + A.escape(a.due_at) : 'Sin vencimiento') + '</small></div><button class="danger-button delete-assignment" data-id="' + a.id + '">Quitar</button></article>'; }).join('') : '<div class="empty-state"><p>No hay asignaciones.</p></div>') + '</div></section></div>';
  }

  function usersPanel() {
    var allowed = A.isSuperAdmin() ? ['colaborador', 'creador_contenido', 'revisor', 'admin', 'super_admin'] : ['colaborador', 'creador_contenido', 'revisor'];
    var allRoles = ['colaborador', 'creador_contenido', 'revisor', 'admin', 'super_admin'];
    return '<div class="studio-columns"><section class="panel"><div class="panel-heading"><div><h2>Agregar usuario al Aula</h2><p>Primero se reutiliza Auth si el correo ya existe; solo se crea una cuenta nueva cuando hace falta.</p></div></div><form id="newUserForm" class="demo-inline-form"><label>Nombre completo<input name="name" required></label><label>Correo<input name="email" type="email" required></label><label>Rol<select name="role">' + allowed.map(function (r) { return '<option value="' + r + '">' + r + '</option>'; }).join('') + '</select></label><div><button class="primary-button" id="createUserBtn">Vincular / crear</button></div></form></section>' +
      '<section class="panel"><div class="panel-heading"><div><h2>Usuarios y roles</h2><p>Desactivar aquí solo afecta Aula; no bloquea la cuenta Auth compartida.</p></div></div><div class="demo-table-wrap"><table class="demo-table"><thead><tr><th>Usuario</th><th>Rol</th><th>Estado</th><th>Acción</th></tr></thead><tbody>' +
      A.state.users.map(function (u) {
        var self = u.id === A.currentUid(); var canRole = A.isSuperAdmin() && !self; var actorRank = A.profile.role === 'super_admin' ? 50 : 40; var targetRank = { colaborador: 10, creador_contenido: 20, revisor: 30, admin: 40, super_admin: 50 }[u.role] || 10; var canToggle = !self && actorRank > targetRank;
        return '<tr><td><b>' + A.escape(u.full_name) + '</b><br><small>' + A.escape(u.email) + '</small></td><td><select class="role-change" data-id="' + u.id + '" ' + (canRole ? '' : 'disabled') + '>' + allRoles.map(function (r) { return '<option value="' + r + '" ' + (r === u.role ? 'selected' : '') + '>' + r + '</option>'; }).join('') + '</select></td><td><span class="demo-chip ' + (u.is_active ? 'success' : 'warning') + '">' + (u.is_active ? 'Activo' : 'Inactivo') + '</span></td><td>' + (canToggle ? '<button class="' + (u.is_active ? 'danger-button' : 'secondary-button') + ' toggle-user" data-id="' + u.id + '">' + (u.is_active ? 'Desactivar' : 'Reactivar') + '</button>' : '<small class="demo-muted">Protegido</small>') + '</td></tr>';
      }).join('') + '</tbody></table></div></section></div>';
  }

  function complianceStateLabel(state) {
    return { compliant:'Al día', expiring:'Por vencer', overdue:'Vencida', expired:'Evidencia vencida', in_progress:'En progreso', assigned:'Asignada', not_assigned:'Sin matrícula' }[state] || state;
  }

  function compliancePanel() {
    var d=A.trainingAdmin;
    if(!d) return '<section class="compliance-loading"><div class="experience-loading-mark">A</div><h2>Preparando Motor de Formación…</h2><p>Cargando cargos, competencias, rutas y cumplimiento.</p></section>';
    A.ui.complianceSection=A.ui.complianceSection||'overview';
    var section=A.ui.complianceSection, positions=d.positions||[], competencies=d.competencies||[], paths=d.paths||[], members=d.members||[], rows=d.compliance||[], snap=d.snapshot||{};
    A.ui.selectedPosition=A.ui.selectedPosition||((positions[0]||{}).id||'');
    A.ui.selectedPath=A.ui.selectedPath||((paths[0]||{}).id||'');
    var pos=positions.find(function(x){return x.id===A.ui.selectedPosition;})||positions[0]||null;
    var path=paths.find(function(x){return x.id===A.ui.selectedPath;})||paths[0]||null;
    var nav=[['overview','Resumen'],['positions','Cargos y personas'],['competencies','Competencias'],['paths','Rutas'],['automation','Automatizaciones'],['matrix','Cumplimiento']];
    var top='<section class="compliance-hero"><div><span class="eyebrow-light">Motor de formación y cumplimiento</span><h2>Del cargo a la evidencia, con trazabilidad completa.</h2><p>Cargos → competencias → rutas → capacitaciones → vencimientos → certificados → recertificación → analítica.</p></div><div class="compliance-hero-score"><strong>'+Number(snap.compliance_percent||0)+'%</strong><span>cumplimiento</span></div></section><div class="compliance-tabs">'+nav.map(function(n){return '<button data-compliance-section="'+n[0]+'" class="'+(section===n[0]?'active':'')+'">'+n[1]+'</button>';}).join('')+'</div>';

    var body='';
    if(section==='overview'){
      body='<div class="compliance-overview"><div class="compliance-metrics"><article><span>Cargos</span><strong>'+Number(snap.positions||0)+'</strong></article><article><span>Competencias</span><strong>'+Number(snap.competencies||0)+'</strong></article><article><span>Rutas</span><strong>'+Number(snap.paths||0)+'</strong></article><article><span>Personas con cargo</span><strong>'+Number(snap.users_with_position||0)+'</strong></article><article><span>Obligaciones</span><strong>'+Number(snap.requirements||0)+'</strong></article><article><span>Vencidas</span><strong>'+Number(snap.overdue||0)+'</strong></article></div><div class="compliance-overview-grid"><section class="panel-card compliance-flow-card"><span class="eyebrow">Flujo automático</span><h3>La asignación ya no depende de trabajo manual</h3><div class="compliance-flow"><span>Cargo</span><b>→</b><span>Competencias</span><b>→</b><span>Ruta</span><b>→</b><span>Curso</span><b>→</b><span>Evidencia</span></div><div class="compliance-flow-actions"><button id="syncTrainingEngine" class="primary-button">Sincronizar ahora</button></div></section><section class="panel-card compliance-alert-card"><span class="eyebrow">Atención</span><h3>'+Number(snap.without_position||0)+' personas sin cargo formativo</h3><p>'+Number(snap.due_soon||0)+' obligaciones están próximas a vencer y '+Number(snap.overdue||0)+' requieren gestión.</p></section></div></div>';
    } else if(section==='positions'){
      body='<div class="compliance-two-column"><section class="panel-card compliance-catalog-panel"><div class="section-title-row"><div><span class="eyebrow">Catálogo</span><h3>Cargos y categorías</h3></div></div><div class="compliance-position-list">'+positions.map(function(x){return '<button class="'+(pos&&x.id===pos.id?'active':'')+'" data-position-id="'+x.id+'"><span class="compliance-position-icon">◎</span><div><strong>'+A.escape(x.name)+'</strong><small>'+A.escape(x.department||'Sin dependencia')+'</small></div></button>';}).join('')+'</div><form id="newPositionForm" class="compliance-create-box"><h4>Nuevo cargo</h4><input name="name" placeholder="Nombre del cargo" required><input name="department" placeholder="Dependencia"><button class="primary-button compact">Crear</button></form></section><section class="panel-card compliance-position-detail">'+(pos?'<span class="eyebrow">Configuración del cargo</span><h2>'+A.escape(pos.name)+'</h2><p>'+A.escape(pos.description||'Configura rutas y personas asociadas.')+'</p><h4>Rutas obligatorias</h4><div class="compliance-path-toggle-grid">'+paths.map(function(p){var linked=(d.position_paths||[]).some(function(v){return v.position_id===pos.id&&v.path_id===p.id;});return '<label class="route-toggle"><input class="position-path-toggle" type="checkbox" data-position="'+pos.id+'" data-path="'+p.id+'" '+(linked?'checked':'')+'><span><strong>'+A.escape(p.name)+'</strong><small>'+A.escape(p.description||'Ruta formativa')+'</small></span></label>';}).join('')+'</div><h4>Personas</h4><div class="compliance-people-list">'+members.filter(function(m){return m.is_active;}).map(function(m){return '<div class="compliance-person-row"><div class="compliance-person-avatar">'+A.escape(String(m.full_name||'U').split(/\s+/).slice(0,2).map(function(x){return x[0];}).join('').toUpperCase())+'</div><div><strong>'+A.escape(m.full_name)+'</strong><small>'+A.escape(m.email)+'</small></div><select class="person-position" data-user="'+m.id+'"><option value="">Sin cargo</option>'+positions.filter(function(p){return p.is_active;}).map(function(p){return '<option value="'+p.id+'" '+(m.job_position_id===p.id?'selected':'')+'>'+A.escape(p.name)+'</option>';}).join('')+'</select></div>';}).join('')+'</div>':'<div class="compliance-empty-compact">Crea un cargo para comenzar.</div>')+'</section></div>';
    } else if(section==='competencies'){
      body='<div class="compliance-competency-layout"><section class="panel-card"><div class="section-title-row"><div><span class="eyebrow">Matriz</span><h3>Competencias por cargo</h3></div><select id="competencyPositionSelect">'+positions.map(function(p){return '<option value="'+p.id+'" '+(pos&&p.id===pos.id?'selected':'')+'>'+A.escape(p.name)+'</option>';}).join('')+'</select></div><div class="compliance-competency-grid">'+competencies.map(function(x){var map=(d.position_competencies||[]).find(function(v){return pos&&v.position_id===pos.id&&v.competency_id===x.id;});return '<label class="competency-toggle"><input class="position-competency-toggle" type="checkbox" data-position="'+(pos?pos.id:'')+'" data-competency="'+x.id+'" '+(map?'checked':'')+'><div><strong>'+A.escape(x.name)+'</strong><small>'+A.escape(x.category)+'</small></div><span>N'+(map?map.required_level:1)+'</span></label>';}).join('')+'</div></section><section class="panel-card compliance-create-competency"><span class="eyebrow">Nueva competencia</span><h3>Ampliar catálogo</h3><form id="newCompetencyForm" class="stack-form"><input name="name" placeholder="Nombre" required><select name="category"><option>institucional</option><option>cumplimiento</option><option>digital</option><option>gestion</option><option>servicio</option></select><textarea name="description" placeholder="Descripción"></textarea><button class="primary-button">Crear competencia</button></form></section></div>';
    } else if(section==='paths'){
      body='<div class="compliance-path-layout"><section class="panel-card compliance-path-sidebar"><span class="eyebrow">Rutas</span><div class="compliance-path-list">'+paths.map(function(p){return '<button class="'+(path&&p.id===path.id?'active':'')+'" data-path-id="'+p.id+'"><strong>'+A.escape(p.name)+'</strong><small>v'+p.version+'</small></button>';}).join('')+'</div><form id="newPathForm" class="compliance-create-box"><h4>Nueva ruta</h4><input name="name" placeholder="Nombre de la ruta" required><textarea name="description" placeholder="Descripción"></textarea><button class="primary-button compact">Crear</button></form></section><section class="panel-card compliance-path-builder">'+(path?'<span class="eyebrow">Constructor de ruta</span><h2>'+A.escape(path.name)+'</h2><p>'+A.escape(path.description||'Vincula capacitaciones publicadas y define vigencias.')+'</p><div class="compliance-course-pool-grid">'+A.state.courses.filter(function(c){return c.status==='published';}).map(function(course){var map=(d.path_courses||[]).find(function(v){return v.path_id===path.id&&v.course_id===course.id;});return '<label class="path-course-card"><input class="path-course-toggle" type="checkbox" data-path="'+path.id+'" data-course="'+A.escape(course.id)+'" '+(map?'checked':'')+'><div><strong>'+A.escape(course.title)+'</strong><small>'+(map?'Vence en '+(map.due_days||30)+' días · recertifica '+(map.recertification_months||'sin vigencia'):'No vinculada')+'</small></div></label>';}).join('')+'</div>':'<div class="compliance-empty-path">Crea o selecciona una ruta.</div>')+'</section></div>';
    } else if(section==='automation'){
      body='<div class="compliance-automation"><section class="panel-card compliance-automation-intro"><span class="eyebrow">Automatizaciones</span><h2>Reglas que trabajan por la entidad</h2><p>La arquitectura ya permite asignar rutas por cargo, preparar alertas de vencimiento y gestionar recertificación.</p><button id="syncTrainingEngine" class="primary-button">Sincronizar motor</button></section><div class="compliance-rule-grid">'+(d.rules||[]).map(function(r){return '<article><div class="automation-rule-icon">⚡</div><div class="automation-rule-copy"><strong>'+A.escape(r.name)+'</strong><p>'+A.escape(r.description||'')+'</p></div><div class="automation-rule-footer"><span class="demo-chip '+(r.is_active?'success':'warning')+'">'+(r.is_active?'Activa':'Preparada')+'</span><label class="switch-control"><input class="rule-toggle" data-rule="'+r.id+'" type="checkbox" '+(r.is_active?'checked':'')+'><span></span></label></div></article>';}).join('')+'</div></div>';
    } else {
      A.ui.complianceQuery=A.ui.complianceQuery||''; var q=A.ui.complianceQuery.toLowerCase();
      var filtered=rows.filter(function(r){return !q||(r.full_name+' '+r.position_name+' '+r.path_name+' '+r.course_title).toLowerCase().indexOf(q)>=0;});
      body='<section class="panel-card compliance-matrix"><div class="compliance-matrix-head"><div><span class="eyebrow">Matriz viva</span><h2>Cumplimiento formativo</h2><p>Estado consolidado por persona, cargo, ruta y capacitación.</p></div><div class="compliance-matrix-summary"><span>'+rows.length+' obligaciones</span><span class="warning">'+Number(snap.due_soon||0)+' por vencer</span><span class="danger">'+Number(snap.overdue||0)+' vencidas</span></div></div><div class="search-field compliance-matrix-search"><span>⌕</span><input id="complianceSearch" placeholder="Buscar persona, cargo, ruta o curso…" value="'+A.escape(A.ui.complianceQuery)+'"></div><div class="compliance-table-wrap"><table class="compliance-table"><thead><tr><th>Persona</th><th>Cargo / Ruta</th><th>Capacitación</th><th>Progreso</th><th>Vencimiento</th><th>Estado</th></tr></thead><tbody>'+filtered.map(function(r){return '<tr><td><strong>'+A.escape(r.full_name)+'</strong><small>'+A.escape(r.email)+'</small></td><td><strong>'+A.escape(r.position_name)+'</strong><small>'+A.escape(r.path_name)+'</small></td><td>'+A.escape(r.course_title)+'</td><td><div class="mini-progress"><span style="width:'+Number(r.progress_percent||0)+'%"></span></div><small>'+Number(r.progress_percent||0)+'%</small></td><td>'+(r.due_at?A.escape(r.due_at):'—')+'</td><td><span class="compliance-state '+A.escape(r.compliance_state)+'">'+A.escape(complianceStateLabel(r.compliance_state))+'</span></td></tr>';}).join('')+'</tbody></table></div></section>';
    }
    return '<div class="compliance-center">'+top+body+'</div>';
  }

  function certificatesPanel() {
    var sorted = A.state.certificates.slice().sort(function (a, b) { return Number(b.score) - Number(a.score); });
    return '<div class="studio-columns certificates-layout"><section class="panel"><div class="panel-heading"><div><h2>Ranking y certificados emitidos</h2><p>Resultados persistentes de las rutas de formación.</p></div></div>' +
      (sorted.length ? '<div class="certificate-list">' + sorted.map(function (c, i) { var u = A.user(c.user_id), course = A.course(c.course_id); return '<article class="certificate-row-card"><div class="certificate-rank">#' + (i + 1) + '</div><div class="certificate-main"><b>' + A.escape(u ? u.full_name : 'Usuario') + '</b><span>' + A.escape(course ? course.title : 'Capacitación') + '</span><small>Código: ' + A.escape(c.code) + ' · Puntaje: ' + c.score + '% · Emisión: ' + new Date(c.issued_at).toLocaleDateString('es-CO') + '</small></div><div class="certificate-actions"><a class="secondary-button" href="#/certificate/' + encodeURIComponent(c.code) + '">Abrir</a></div></article>'; }).join('') + '</div>' : '<div class="empty-state"><h3>Aún no hay certificados emitidos</h3></div>') +
      '</section><section class="panel"><div class="panel-heading"><div><h2>Emitir certificado</h2><p>Uso administrativo para regularizaciones o cargas autorizadas.</p></div></div><form id="manualCertForm" class="demo-inline-form"><label>Usuario<select name="user">' + A.state.users.filter(function (u) { return u.is_active; }).map(function (u) { return '<option value="' + u.id + '">' + A.escape(u.full_name) + '</option>'; }).join('') + '</select></label><label>Capacitación<select name="course">' + A.state.courses.map(function (c) { return '<option value="' + A.escape(c.id) + '">' + A.escape(c.title) + '</option>'; }).join('') + '</select></label><label>Puntaje<input name="score" type="number" min="0" max="100" value="95"></label><button class="primary-button">Emitir certificado</button></form></section></div>';
  }

  function bind() {
    document.querySelectorAll('[data-tab]').forEach(function (b) { b.onclick = function () { A.ui.tab = b.getAttribute('data-tab'); A.ui.selectedCourse = null; A.studio(); }; });
    document.querySelectorAll('.edit-course').forEach(function (b) { b.onclick = function () { A.ui.selectedCourse = b.getAttribute('data-id'); A.studio(); }; });
    var back = document.getElementById('backCourses'); if (back) back.onclick = function () { A.ui.selectedCourse = null; A.studio(); };

    var nf = document.getElementById('newCourseForm'); if (nf) nf.onsubmit = async function (e) {
      e.preventDefault(); var f = new FormData(nf), id = 'course-' + Date.now().toString(36) + Math.random().toString(36).slice(2, 7);
      var c = { id: id, title: String(f.get('title')), description: String(f.get('description')), status: 'draft', passing_score: Number(f.get('passing')) || 80, phases: [{ id: A.uid('phase'), title: 'Fase 1 · Contenidos', blocks: [] }], questions: blankQuestions(id) };
      try { await persistCourse(c, 'Capacitación creada: ' + c.title); A.state.courses.unshift(c); A.ui.selectedCourse = c.id; A.toast('Capacitación creada.'); A.studio(); } catch (err) { A.toast(A.errorText(err)); }
    };
    var ef = document.getElementById('editCourseForm'); if (ef) ef.onsubmit = async function (e) {
      e.preventDefault(); var c = A.course(A.ui.selectedCourse), f = new FormData(ef); var old = { title: c.title, description: c.description, passing_score: c.passing_score, status: c.status };
      c.title = String(f.get('title')); c.description = String(f.get('description')); c.passing_score = Math.max(1, Math.min(100, Number(f.get('passing')) || 80)); c.status = String(f.get('status'));
      try { await persistCourse(c); A.toast('Capacitación actualizada.'); A.studio(); } catch (err) { Object.assign(c, old); A.toast(A.errorText(err)); }
    };
    var ab = document.getElementById('addBlockForm'); if (ab) ab.onsubmit = async function (e) {
      e.preventDefault(); var c = A.course(A.ui.selectedCourse), f = new FormData(ab); if (!c.phases.length) c.phases = [{ id: A.uid('phase'), title: 'Fase 1 · Contenidos', blocks: [] }];
      var b = { id: A.uid('block'), title: String(f.get('title')), type: String(f.get('type')), required: f.get('required') === 'on', body: String(f.get('body')), url: String(f.get('url') || '') }; c.phases[c.phases.length - 1].blocks.push(b);
      try { await persistCourse(c, 'Contenido agregado a ' + c.title); A.toast('Contenido agregado.'); A.studio(); } catch (err) { c.phases[c.phases.length - 1].blocks.pop(); A.toast(A.errorText(err)); }
    };
    document.querySelectorAll('.delete-block').forEach(function (b) { b.onclick = async function () { if (!confirm('¿Eliminar este bloque?')) return; var c = A.course(A.ui.selectedCourse), id = b.getAttribute('data-id'), backup = JSON.parse(JSON.stringify(c.phases)); c.phases.forEach(function (p) { p.blocks = (p.blocks || []).filter(function (x) { return x.id !== id; }); }); try { await persistCourse(c, 'Contenido eliminado de ' + c.title); A.studio(); } catch (err) { c.phases = backup; A.toast(A.errorText(err)); } }; });

    var af = document.getElementById('assignForm'); if (af) af.onsubmit = async function (e) {
      e.preventDefault(); var f = new FormData(af), uid = String(f.get('user')), cid = String(f.get('course')), due = String(f.get('due') || '') || null;
      try { var r = await A.rpc('aula_assign_course', { p_user_id: uid, p_course_id: cid, p_due_at: due }); var existing = A.state.assignments.find(function (a) { return a.user_id === uid && a.course_id === cid; }); if (existing) { existing.due_at = due; } else { A.state.assignments.push({ id: r.id, user_id: uid, course_id: cid, due_at: due }); } A.toast('Asignación guardada.'); A.studio(); } catch (err) { A.toast(A.errorText(err)); }
    };
    document.querySelectorAll('.delete-assignment').forEach(function (b) { b.onclick = async function () { var id = b.getAttribute('data-id'); try { await A.rpc('aula_unassign_course', { p_assignment_id: id }); A.state.assignments = A.state.assignments.filter(function (a) { return a.id !== id; }); A.toast('Asignación retirada; historial conservado.'); A.studio(); } catch (err) { A.toast(A.errorText(err)); } }; });

    var uf = document.getElementById('newUserForm'); if (uf) uf.onsubmit = async function (e) {
      e.preventDefault(); var f = new FormData(uf), name = String(f.get('name')).trim(), email = String(f.get('email')).trim().toLowerCase(), role = String(f.get('role')), btn = document.getElementById('createUserBtn'); btn.disabled = true; btn.textContent = 'Procesando…';
      try {
        var linked = await A.rpc('aula_add_existing_user', { p_email: email, p_full_name: name, p_role: role }); var user;
        if (linked && linked.found) { user = { id: linked.user_id, full_name: name, email: email, role: role, is_active: true, must_change_password: false }; A.toast('Cuenta Auth existente vinculada al Aula.'); }
        else { var created = await A.invoke('aula-create-managed-user', { email: email, full_name: name, role: role }); user = { id: created.user.id, full_name: name, email: email, role: role, is_active: true, must_change_password: true }; alert('Usuario creado. Contraseña temporal (se muestra una sola vez):\n\n' + created.temporary_password + '\n\nEl usuario deberá cambiarla al ingresar.'); }
        var pos = A.state.users.findIndex(function (u) { return u.id === user.id; }); if (pos >= 0) A.state.users[pos] = user; else A.state.users.push(user); A.studio();
      } catch (err) { A.toast(A.errorText(err)); } finally { btn.disabled = false; btn.textContent = 'Vincular / crear'; }
    };
    document.querySelectorAll('.role-change').forEach(function (s) { s.onchange = async function () { var u = A.user(s.getAttribute('data-id')), old = u.role, next = s.value; try { await A.rpc('aula_set_member_role', { p_user_id: u.id, p_role: next }); u.role = next; A.toast('Rol actualizado.'); } catch (err) { s.value = old; A.toast(A.errorText(err)); } }; });
    document.querySelectorAll('.toggle-user').forEach(function (b) { b.onclick = async function () { var u = A.user(b.getAttribute('data-id')), next = !u.is_active; try { await A.rpc('aula_set_member_active', { p_user_id: u.id, p_active: next }); u.is_active = next; A.toast(next ? 'Usuario reactivado en Aula.' : 'Usuario desactivado solo en Aula.'); A.studio(); } catch (err) { A.toast(A.errorText(err)); } }; });

    document.querySelectorAll('[data-compliance-section]').forEach(function(b){ b.onclick=function(){ A.ui.complianceSection=b.getAttribute('data-compliance-section'); A.studio(); }; });
    document.querySelectorAll('[data-position-id]').forEach(function(b){ b.onclick=function(){ A.ui.selectedPosition=b.getAttribute('data-position-id'); A.studio(); }; });
    document.querySelectorAll('[data-path-id]').forEach(function(b){ b.onclick=function(){ A.ui.selectedPath=b.getAttribute('data-path-id'); A.studio(); }; });

    var np=document.getElementById('newPositionForm'); if(np) np.onsubmit=async function(e){e.preventDefault();var x=new FormData(np);try{await A.rpc('aula_training_save_position',{p_item:{name:String(x.get('name')),department:String(x.get('department')||''),position_type:'cargo'}});await A.loadTrainingAdmin(true);A.toast('Cargo creado.');A.studio();}catch(err){A.toast(A.errorText(err));}};
    var nc=document.getElementById('newCompetencyForm'); if(nc) nc.onsubmit=async function(e){e.preventDefault();var x=new FormData(nc);try{await A.rpc('aula_training_save_competency',{p_item:{name:String(x.get('name')),category:String(x.get('category')),description:String(x.get('description')||'')}});await A.loadTrainingAdmin(true);A.toast('Competencia creada.');A.studio();}catch(err){A.toast(A.errorText(err));}};
    var npath=document.getElementById('newPathForm'); if(npath) npath.onsubmit=async function(e){e.preventDefault();var x=new FormData(npath);try{var r=await A.rpc('aula_training_save_path',{p_item:{name:String(x.get('name')),description:String(x.get('description')||''),version:1}});A.ui.selectedPath=r.id;await A.loadTrainingAdmin(true);A.toast('Ruta creada.');A.studio();}catch(err){A.toast(A.errorText(err));}};

    document.querySelectorAll('.person-position').forEach(function(s){s.onchange=async function(){try{await A.rpc('aula_training_set_user_position',{p_user_id:s.getAttribute('data-user'),p_position_id:s.value||null,p_reason:'Actualización desde Gestión Aula'});await A.loadTrainingAdmin(true);A.toast('Cargo y rutas actualizados.');A.studio();}catch(err){A.toast(A.errorText(err));}};});
    document.querySelectorAll('.position-path-toggle').forEach(function(x){x.onchange=async function(){try{await A.rpc('aula_training_set_position_path',{p_position_id:x.getAttribute('data-position'),p_path_id:x.getAttribute('data-path'),p_enabled:x.checked,p_due_days:30,p_recertification_months:null});await A.loadTrainingAdmin(true);A.toast('Ruta del cargo actualizada.');A.studio();}catch(err){x.checked=!x.checked;A.toast(A.errorText(err));}};});
    document.querySelectorAll('.position-competency-toggle').forEach(function(x){x.onchange=async function(){try{await A.rpc('aula_training_set_position_competency',{p_position_id:x.getAttribute('data-position'),p_competency_id:x.getAttribute('data-competency'),p_enabled:x.checked,p_required_level:1,p_weight:1});await A.loadTrainingAdmin(true);A.toast('Matriz de competencias actualizada.');A.studio();}catch(err){x.checked=!x.checked;A.toast(A.errorText(err));}};});
    document.querySelectorAll('.path-course-toggle').forEach(function(x){x.onchange=async function(){try{await A.rpc('aula_training_set_path_course',{p_path_id:x.getAttribute('data-path'),p_course_id:x.getAttribute('data-course'),p_enabled:x.checked,p_sort_order:100,p_due_days:30,p_recertification_months:12});await A.loadTrainingAdmin(true);A.toast('Contenido de la ruta actualizado.');A.studio();}catch(err){x.checked=!x.checked;A.toast(A.errorText(err));}};});
    document.querySelectorAll('.rule-toggle').forEach(function(x){x.onchange=async function(){try{await A.rpc('aula_training_set_rule_active',{p_rule_id:x.getAttribute('data-rule'),p_active:x.checked});await A.loadTrainingAdmin(true);A.toast('Automatización actualizada.');A.studio();}catch(err){x.checked=!x.checked;A.toast(A.errorText(err));}};});
    var sync=document.getElementById('syncTrainingEngine'); if(sync) sync.onclick=async function(){sync.disabled=true;try{await A.rpc('aula_training_sync_all');await A.loadTrainingAdmin(true);A.toast('Motor sincronizado.');A.studio();}catch(err){A.toast(A.errorText(err));sync.disabled=false;}};
    var cps=document.getElementById('competencyPositionSelect'); if(cps)cps.onchange=function(){A.ui.selectedPosition=cps.value;A.studio();};
    var cs=document.getElementById('complianceSearch'); if(cs)cs.oninput=function(){A.ui.complianceQuery=cs.value;A.studio();};

    var cf = document.getElementById('manualCertForm'); if (cf) cf.onsubmit = async function (e) {
      e.preventDefault(); var f = new FormData(cf), uid = String(f.get('user')), cid = String(f.get('course')), score = Math.max(0, Math.min(100, Number(f.get('score')) || 0));
      try { var r = await A.rpc('aula_issue_certificate', { p_user_id: uid, p_course_id: cid, p_score: score }); var existing = A.cert(uid, cid); if (!existing) A.state.certificates.push({ id: A.uid('cert'), code: r.code, user_id: uid, course_id: cid, score: score, issued_at: new Date().toISOString() }); A.toast('Certificado emitido.'); A.studio(); } catch (err) { A.toast(A.errorText(err)); }
    };
  }

  A.studio = function () {
    if (!A.canManage()) { location.hash = '#/'; return; }
    if (!A.canManageUsers() && A.ui.tab !== 'courses') A.ui.tab = 'courses';
    var body = A.ui.tab === 'courses' ? coursePanel() : A.ui.tab === 'assignments' ? assignmentsPanel() : A.ui.tab === 'users' ? usersPanel() : A.ui.tab === 'compliance' ? compliancePanel() : certificatesPanel();
    var html = '<div class="page admin-page studio-single-page"><section class="admin-hero integrated-admin-hero"><div><span class="eyebrow-light">Gestión · Constructor de Aula</span><h1>Administra formación, cumplimiento y evidencia.</h1><p>Capacitaciones, contenidos, asignaciones, usuarios, rutas, vencimientos, certificados y analítica en una sola experiencia.</p></div><div class="admin-role"><strong>' + A.escape(A.profile.role) + '</strong><span>Rol activo</span></div></section>' + tabs() + '<div class="studio-tab-stage">' + body + '</div></div>';
    document.getElementById('root').innerHTML = A.shell(html); A.bindShell(); bind();
    if (A.ui.tab === 'compliance' && !A.trainingAdmin && !A.ui.trainingAdminLoading) {
      A.ui.trainingAdminLoading = true;
      A.loadTrainingAdmin().then(function(){ A.ui.trainingAdminLoading=false; if(A.ui.tab==='compliance')A.studio(); }).catch(function(err){ A.ui.trainingAdminLoading=false; A.toast(A.errorText(err)); });
    }
  };
})(window);
