(function(w){
var A=w.AulaDemo;
function tabs(){return '<div class="tab-bar"><button data-tab="courses" class="'+(A.ui.tab==='courses'?'active':'')+'">Capacitaciones</button><button data-tab="assignments" class="'+(A.ui.tab==='assignments'?'active':'')+'">Asignaciones</button><button data-tab="users" class="'+(A.ui.tab==='users'?'active':'')+'">Usuarios y roles</button><button data-tab="certificates" class="'+(A.ui.tab==='certificates'?'active':'')+'">Ranking y certificados</button></div>';}
function futureDate(days){var d=new Date();d.setDate(d.getDate()+days);return d.toISOString().slice(0,10);}
function blankQuestions(id){return Array.from({length:10}).map(function(_,i){return{id:id+'-q'+i,prompt:'Pregunta demostrativa '+(i+1),options:['Opción A','Opción B','Opción C','Opción D'],correct:0};});}
function coursePanel(){
 if(A.ui.selectedCourse){
  var c=A.course(A.ui.selectedCourse);if(!c){A.ui.selectedCourse=null;return coursePanel();}
  return '<div class="studio-columns"><section class="panel"><div class="panel-heading"><div><h2>Editar capacitación</h2><p>Los cambios quedan guardados en este navegador.</p></div></div><form id="editCourseForm" class="demo-inline-form"><label>Título<input name="title" value="'+A.escape(c.title)+'" required></label><label>Nota mínima<input name="passing" type="number" min="1" max="100" value="'+c.passing_score+'" required></label><label class="span-2">Descripción<textarea name="description" rows="4">'+A.escape(c.description)+'</textarea></label><label>Estado<select name="status"><option value="published" '+(c.status==='published'?'selected':'')+'>Publicado</option><option value="draft" '+(c.status==='draft'?'selected':'')+'>Borrador</option></select></label><div class="demo-actions"><button class="primary-button">Guardar cambios</button><button type="button" class="secondary-button" id="backCourses">Volver</button></div></form></section>'+
  '<section class="panel"><div class="panel-heading"><div><h2>Contenido</h2><p>Fases y bloques de la ruta.</p></div></div>'+
  c.phases.map(function(p){return '<div style="margin-bottom:20px"><h3>'+A.escape(p.title)+'</h3>'+(p.blocks||[]).map(function(b){return '<div class="block-admin-row"><div><b>'+A.escape(b.title)+'</b><small style="display:block">'+A.escape(b.type)+(b.required?' · obligatorio':' · opcional')+'</small></div><button class="secondary-button delete-block" data-id="'+A.escape(b.id)+'">Eliminar</button></div>';}).join('')+'</div>';}).join('')+
  '<form id="addBlockForm" class="demo-inline-form"><label>Título<input name="title" required></label><label>Tipo<select name="type"><option value="reading">Lectura</option><option value="video">Video</option><option value="presentation">Presentación</option><option value="game">Juego</option><option value="validation">Validación</option></select></label><label class="span-2">Contenido<textarea name="body" rows="3" required></textarea></label><label><input name="required" type="checkbox" checked> Obligatorio</label><div><button class="primary-button">Agregar bloque</button></div></form></section></div>';
 }
 return '<div class="studio-columns"><section class="panel"><div class="panel-heading"><div><h2>Nueva capacitación</h2><p>Crea una nueva ruta demostrativa.</p></div></div><form id="newCourseForm" class="demo-inline-form"><label>Título<input name="title" required></label><label>Nota mínima<input name="passing" type="number" min="1" max="100" value="80" required></label><label class="span-2">Descripción<textarea name="description" rows="4" required></textarea></label><button class="primary-button">Crear capacitación</button></form></section>'+
 '<section class="panel"><div class="panel-heading"><div><h2>Capacitaciones</h2><p>'+A.state.courses.length+' registros en la demo.</p></div></div><div class="assignment-list">'+A.state.courses.map(function(c){return '<article class="assignment-card"><div><b>'+A.escape(c.title)+'</b><span>'+A.escape(c.description)+'</span><small>'+A.escape(c.status)+' · '+A.percent('u-admin',c)+'% progreso admin</small></div><button class="secondary-button edit-course" data-id="'+A.escape(c.id)+'">Editar</button></article>';}).join('')+'</div></section></div>';
}
function assignmentsPanel(){
 return '<div class="studio-columns"><section class="panel"><div class="panel-heading"><div><h2>Nueva asignación</h2><p>Relaciona un usuario con una capacitación.</p></div></div><form id="assignForm" class="demo-inline-form"><label>Usuario<select name="user">'+A.state.users.filter(function(u){return u.is_active;}).map(function(u){return '<option value="'+u.id+'">'+A.escape(u.full_name)+'</option>';}).join('')+'</select></label><label>Capacitación<select name="course">'+A.state.courses.map(function(c){return '<option value="'+c.id+'">'+A.escape(c.title)+'</option>';}).join('')+'</select></label><label>Vencimiento<input name="due" type="date" value="'+futureDate(15)+'"></label><div><button class="primary-button">Asignar</button></div></form></section>'+
 '<section class="panel"><div class="panel-heading"><div><h2>Asignaciones activas</h2><p>Vista de trazabilidad de ejemplo.</p></div></div><div class="assignment-list">'+A.state.assignments.map(function(a){var u=A.user(a.user_id),c=A.course(a.course_id);return '<article class="assignment-card"><div><b>'+A.escape(c?c.title:'Curso eliminado')+'</b><span>'+A.escape(u?u.full_name:'Usuario eliminado')+'</span><small>'+(a.due_at?'Vence '+A.escape(a.due_at):'Sin vencimiento')+'</small></div><button class="danger-button delete-assignment" data-id="'+a.id+'">Quitar</button></article>';}).join('')+'</div></section></div>';
}
function usersPanel(){
 var roles=['colaborador','creador_contenido','admin','super_admin'];
 return '<div class="studio-columns"><section class="panel"><div class="panel-heading"><div><h2>Crear usuario demo</h2><p>No se crea ninguna cuenta real.</p></div></div><form id="newUserForm" class="demo-inline-form"><label>Nombre completo<input name="name" required></label><label>Correo<input name="email" type="email" required></label><label>Rol<select name="role">'+roles.map(function(r){return '<option value="'+r+'">'+r+'</option>';}).join('')+'</select></label><div><button class="primary-button">Crear usuario</button></div></form></section>'+
 '<section class="panel"><div class="panel-heading"><div><h2>Usuarios y roles</h2><p>Administración local de ejemplo.</p></div></div><div class="demo-table-wrap"><table class="demo-table"><thead><tr><th>Usuario</th><th>Rol</th><th>Estado</th><th>Acción</th></tr></thead><tbody>'+
 A.state.users.map(function(u){return '<tr><td><b>'+A.escape(u.full_name)+'</b><br><small>'+A.escape(u.email)+'</small></td><td><select class="role-change" data-id="'+u.id+'" '+(u.id==='u-admin'?'disabled':'')+'>'+roles.map(function(r){return '<option value="'+r+'" '+(r===u.role?'selected':'')+'>'+r+'</option>';}).join('')+'</select></td><td><span class="demo-chip '+(u.is_active?'success':'warning')+'">'+(u.is_active?'Activo':'Inactivo')+'</span></td><td>'+(u.id==='u-admin'?'<small class="demo-muted">Cuenta demo</small>':'<button class="'+(u.is_active?'danger-button':'secondary-button')+' toggle-user" data-id="'+u.id+'">'+(u.is_active?'Desactivar':'Reactivar')+'</button>')+'</td></tr>';}).join('')+
 '</tbody></table></div></section></div>';
}
function certificatesPanel(){
 var sorted=A.state.certificates.slice().sort(function(a,b){return b.score-a.score;});
 return '<div class="studio-columns certificates-layout"><section class="panel"><div class="panel-heading"><div><h2>Ranking y certificados emitidos</h2><p>Resultados generados dentro de la demo.</p></div></div>'+
 (sorted.length?'<div class="certificate-list">'+sorted.map(function(c,i){var u=A.user(c.user_id),course=A.course(c.course_id);return '<article class="certificate-row-card"><div class="certificate-rank">#'+(i+1)+'</div><div class="certificate-main"><b>'+A.escape(u?u.full_name:'Usuario')+'</b><span>'+A.escape(course?course.title:'Capacitación')+'</span><small>Código: '+A.escape(c.code)+' · Puntaje: '+c.score+'% · Emisión: '+new Date(c.issued_at).toLocaleDateString('es-CO')+'</small></div><div class="certificate-actions"><a class="secondary-button" href="#/certificate/'+encodeURIComponent(c.code)+'">Abrir</a></div></article>';}).join('')+'</div>':'<div class="empty-state"><h3>Aún no hay certificados emitidos</h3><p>Completa una capacitación o genera un certificado demo.</p></div>')+
 '</section><section class="panel"><div class="panel-heading"><div><h2>Demo comercial</h2><p>Genera un certificado de muestra sin presentar el examen.</p></div></div><form id="manualCertForm" class="demo-inline-form"><label>Capacitación<select name="course">'+A.state.courses.map(function(c){return '<option value="'+c.id+'">'+A.escape(c.title)+'</option>';}).join('')+'</select></label><label>Puntaje<input name="score" type="number" min="80" max="100" value="95"></label><button class="primary-button">Generar certificado demo</button></form></section></div>';
}
function bind(){
 document.querySelectorAll('[data-tab]').forEach(function(b){b.onclick=function(){A.ui.tab=b.getAttribute('data-tab');A.ui.selectedCourse=null;A.studio();};});
 document.querySelectorAll('.edit-course').forEach(function(b){b.onclick=function(){A.ui.selectedCourse=b.getAttribute('data-id');A.studio();};});
 var back=document.getElementById('backCourses');if(back)back.onclick=function(){A.ui.selectedCourse=null;A.studio();};
 var nf=document.getElementById('newCourseForm');if(nf)nf.onsubmit=function(e){e.preventDefault();var f=new FormData(nf),id=A.uid('course'),c={id:id,title:String(f.get('title')),description:String(f.get('description')),status:'draft',passing_score:Number(f.get('passing'))||80,phases:[{id:A.uid('phase'),title:'Fase 1 · Contenidos',blocks:[]}],questions:blankQuestions(id)};A.state.courses.unshift(c);A.save();A.log('Capacitación creada: '+c.title);A.ui.selectedCourse=id;A.studio();};
 var ef=document.getElementById('editCourseForm');if(ef)ef.onsubmit=function(e){e.preventDefault();var c=A.course(A.ui.selectedCourse),f=new FormData(ef);c.title=String(f.get('title'));c.description=String(f.get('description'));c.passing_score=Math.max(1,Math.min(100,Number(f.get('passing'))||80));c.status=String(f.get('status'));A.save();A.log('Capacitación actualizada: '+c.title);A.toast('Capacitación actualizada.');A.studio();};
 var ab=document.getElementById('addBlockForm');if(ab)ab.onsubmit=function(e){e.preventDefault();var c=A.course(A.ui.selectedCourse),f=new FormData(ab);if(!c.phases.length)c.phases=[{id:A.uid('phase'),title:'Fase 1 · Contenidos',blocks:[]}];c.phases[c.phases.length-1].blocks.push({id:A.uid('block'),title:String(f.get('title')),type:String(f.get('type')),required:f.get('required')==='on',body:String(f.get('body'))});A.save();A.log('Contenido agregado a '+c.title);A.studio();};
 document.querySelectorAll('.delete-block').forEach(function(b){b.onclick=function(){var c=A.course(A.ui.selectedCourse),id=b.getAttribute('data-id');c.phases.forEach(function(p){p.blocks=p.blocks.filter(function(x){return x.id!==id;});});A.save();A.studio();};});
 var af=document.getElementById('assignForm');if(af)af.onsubmit=function(e){e.preventDefault();var f=new FormData(af),u=String(f.get('user')),c=String(f.get('course'));if(A.state.assignments.some(function(a){return a.user_id===u&&a.course_id===c;})){A.toast('Esa asignación ya existe.');return;}A.state.assignments.push({id:A.uid('as'),user_id:u,course_id:c,due_at:String(f.get('due')||'')});A.save();A.log('Nueva asignación creada.');A.studio();};
 document.querySelectorAll('.delete-assignment').forEach(function(b){b.onclick=function(){A.state.assignments=A.state.assignments.filter(function(a){return a.id!==b.getAttribute('data-id');});A.save();A.studio();};});
 var uf=document.getElementById('newUserForm');if(uf)uf.onsubmit=function(e){e.preventDefault();var f=new FormData(uf);A.state.users.push({id:A.uid('u'),full_name:String(f.get('name')),email:String(f.get('email')),role:String(f.get('role')),is_active:true});A.save();A.log('Usuario demo creado: '+String(f.get('name')));A.studio();};
 document.querySelectorAll('.role-change').forEach(function(s){s.onchange=function(){var u=A.user(s.getAttribute('data-id'));if(u){u.role=s.value;A.save();A.log('Rol actualizado para '+u.full_name);A.toast('Rol actualizado.');}};});
 document.querySelectorAll('.toggle-user').forEach(function(b){b.onclick=function(){var u=A.user(b.getAttribute('data-id'));if(u){u.is_active=!u.is_active;A.save();A.log((u.is_active?'Usuario reactivado: ':'Usuario desactivado: ')+u.full_name);A.studio();}};});
 var cf=document.getElementById('manualCertForm');if(cf)cf.onsubmit=function(e){e.preventDefault();var f=new FormData(cf),cid=String(f.get('course')),existing=A.cert('u-admin',cid);if(existing){location.hash='#/certificate/'+existing.code;return;}var code='CERT-DEMO-'+new Date().getFullYear()+'-'+String(A.state.certificates.length+1).padStart(4,'0');A.state.certificates.push({id:A.uid('cert'),code:code,user_id:'u-admin',course_id:cid,score:Math.max(80,Math.min(100,Number(f.get('score'))||95)),issued_at:new Date().toISOString()});A.save();A.log('Certificado demo generado: '+code);location.hash='#/certificate/'+code;};
}
A.studio=function(){
 var body=A.ui.tab==='courses'?coursePanel():A.ui.tab==='assignments'?assignmentsPanel():A.ui.tab==='users'?usersPanel():certificatesPanel();
 var html='<div class="page admin-page"><section class="admin-hero"><div><span class="eyebrow-light">Gestión · Constructor de Aula</span><h1>Crea toda la capacitación desde dentro.</h1><p>Administra rutas, contenidos, asignaciones, usuarios y certificados sin modificar código.</p></div><div class="admin-role"><strong>super_admin</strong><span>Rol activo demo</span></div></section>'+tabs()+body+'<div class="demo-actions" style="margin-top:24px"><button id="resetDemo" class="secondary-button">Restablecer datos demo</button></div></div>';
 document.getElementById('root').innerHTML=A.shell(html);A.bindShell();bind();document.getElementById('resetDemo').onclick=function(){if(confirm('¿Restablecer todos los datos locales de la demo?')){A.reset();A.toast('Demo restablecida.');A.studio();}};
};
})(window);